services/vrrp/router: VRRP router
Introduce VRRP router class which handles VRRP.

Cc: yuta-hamada <yuta.hamada.z02@gimal.com>
Signed-off-by: Isaku Yamahata <yamahata@valinux.co.jp>
---
Changes v4 -> v5:
- router.py: vrrp_config_change_request AttributeError
  AttributeError: 'VRRPRouterV3' object has no attribute 'address_owner'

Changes v3 -> v4:
- eventlet

Changes v2 -> v3:
- comment

Changes v1 -> v2:
- dynamic configuration change
- wrong priority comparison